import fs from "node:fs";
import path from "node:path";
import swaggerJsdoc from "swagger-jsdoc";

const rootDir = process.cwd();

const options = {
  definition: {
    openapi: "3.0.3",
    info: {
      title: "Product API",
      version: "1.0.0",
      description: "Product management endpoints",
    },
    servers: [
      {
        url: "/api/v1",
        description: "Current API server",
      },
    ],
    components: {
      securitySchemes: {
        bearerAuth: {
          type: "http",
          scheme: "bearer",
          bearerFormat: "JWT",
        },
      },
      schemas: {
        Product: {
          type: "object",
          properties: {
            productId: { type: "string", example: "b3f1c2a4-..." },
            productName: { type: "string" },
            productDescription: { type: "string" },
            productImage: { type: "string" },
            productPrice: { type: "number" },
            productSalePrice: { type: "number" },
            productRating: { type: "number" },
            productStock: { type: "integer" },
            productCategory: { type: "string" },
            productStatus: { type: "string", default: "active" },
            tags: { type: "array", items: { type: "string" } },
          },
        },
        ProductInput: {
          type: "object",
          required: ["productName"],
          properties: {
            productName: { type: "string" },
            productDescription: { type: "string" },
            productPrice: { type: "number" },
            productSalePrice: { type: "number" },
            productCategory: { type: "string" },
            productStock: { type: "integer" },
            tags: { type: "array", items: { type: "string" } },
          },
        },
        SuccessResponse: {
          type: "object",
          properties: {
            success: { type: "boolean", example: true },
            message: { type: "string" },
            data: {},
          },
        },
        ErrorResponse: {
          type: "object",
          properties: {
            success: { type: "boolean", example: false },
            message: { type: "string" },
          },
        },
      },
    },
  },
  // swagger-jsdoc scans the source route files only during the build.
  // The generated TypeScript module is what the runtime/serverless bundle uses.
  apis: [path.join(rootDir, "src/routes/*.ts")],
};

const spec = swaggerJsdoc(options);
const outputPath = path.join(rootDir, "src/docs/swagger.generated.ts");

const output = `// AUTO-GENERATED FILE - DO NOT EDIT.\n// Generated by src/docs/generate-swagger.ts during the build.\n\nexport const swaggerSpec = ${JSON.stringify(spec, null, 2)} as const;\n`;

fs.writeFileSync(outputPath, output, "utf8");

const pathCount = Object.keys(spec.paths ?? {}).length;
console.log(`Generated OpenAPI specification with ${pathCount} endpoint paths.`);

if (pathCount === 0) {
  throw new Error(
    "OpenAPI generation produced zero endpoint paths. Check the Swagger route annotations and source glob.",
  );
}
